language: node_js

matrix:
  allow_failures:
    - node_js: '4.4'
  include:
    - node_js: '5.11'
    - node_js: '6.2'
      env:
        - secure: "evRDob9sRCZln1RSaHwfQyg4lKr3AqvYQUYJ6KFXaUrDM6vuQFoYeuqQdQgNzVGXP9Jf/HLX5tVqWO+dcRlv3wIA0IWzn94uVzdxnzDXsvzRloPNQM4MmV/xfwkPuXLKjDhIBIo7lILV6AxjhxNQvXy43HjYuazxXB+ayhfGmkIrJ69FIeyzZnFE/Gm0VW1LiMjdCUt/MniEkg3qIhugAah1y9p5c8N0yDMkQ11DkXE8s8e1jIc1MKem+NVijI0FtQvBh+ua/CQNbq5PIJ3HXggDziDTiOq0NS/cbE+zIeh3k+VPt+RWCw+GPzpqWFOjiYdYCItjbOPPe9ebe6VQuDBhUmREf0f6coXlKTVCIKEqm7GGTcLU+giX3hQpLOLK8JiMlSOUEAeZS/rnH6RKPJxk423iO7oaVO9A4tUbyLR69bovWCpxY9D4fzsKthdZ44YzBbQiqD8hTdkyY1EIRQhhoISOcnoC7+jZTF5gicYth/cGjL1HTJ/JSwXtV9hyeKrDAi/y64JMWL5ggUFnXqPNbmYddjDq8SKDAstR1s9AbnkPjj1iVafi0pE4a5j5REYHqlsb/sLbSJ+ZHeo2QA5RzKB9i2kbtRWvbfmqhH4HE6Xnto7o1rVv21/b1vuvpe3q5+aR1gm6JoaX4gdbLdBYZK3tTLv8kcq28rpQVSw="
    - node_js: '6.2'
      env:
        - DISABLE_TESTS=true
        - LINTING=true

sudo: false

install:
  - travis_retry npm install

script:
  - if [[ -z "$DISABLE_TESTS" ]]; then npm test; fi
  - if [[ ! -z "$LINTING" ]]; then npm run lint; fi

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
