language: node_js

matrix:
  allow_failures:
    - node_js: '4.4'
  include:
    - node_js: '5.11'
    - node_js: '6.2'
      env:
        - secure: "mYv4BgSJFZHAuIVWZpuNpqj+8QfxZeUdfuaiBvHpRG1RKgYJu/ct7/IOmQFuXwcsxtW/qEDnRR2Ko+4UCEq11EELI2bKoSqi6kNANyvGX7JipeitXpwPT181aeDZOfg+Q0glacodZa3sVOgISdziOgbs4RiMamo/hzi/wgg3SG9pL8hur1paL6xL0Pn1IN07YnDK5C3Cijtgn6IeUsXehdcuVEmR48UqXtOJ66NnNc9GTxl7n+BAVBobZuAPxWKgcC2C95ks9wF2ySQItQlThnQL1mgrIqt9rnec17oTk+Ml9HXGeF+ZG3ioHhsMXWWvYh2MZxQqz94S42iTvzShg4BECuZfmwz4eAeUlRQaZIm9Z9BhV/5pW501F1Ku4i2kX9borYyZQLOEtLGPzSSFpQyWE4Sq82h/gNg070dNjNeBX9xLaJJcz5vex0yuKr42CGtiJc8s9q2u8E8aGv8yGBzHtEYLkBDyEo8TB666vBmGm0ZaKrKk6OVpGfxgj0EmE4euzrpS4JJp5JT4NcIlQOajYnh+NEpPYrTe3lB4C0DZ+AowThcZvqyKWhXe4Go9orpgG5KKxquC/wb3aH+XNhSzVXBpRlU7pfM++/rccepZJ5wYRecgTptTi/TaO8YwxQ32mWHBAtH+Y9csIpVnhU9PFV5M1lYPzIu3/wfo5AQ="
    - node_js: '6.2'
      env:
        - DISABLE_TESTS=true
        - LINTING=true

sudo: false

install:
  - travis_retry npm install

script:
  - if [[ -z "$DISABLE_TESTS" ]]; then npm test; fi
  - if [[ ! -z "$LINTING" ]]; then npm run lint; fi

after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
